### ISSUE TITLE
mu rounds to 0.0 in params dataframe when simulated along priors 

### ISSUE THREAD

**Issue by thegreatlizzyator** [thegreatlizzyator/ecophylo#14]

**Comment by gowachin** [comment]
Bug :

```
import ecophylo
t = ecophylo.dosimuls(nsim = 10, samples = 3063, deme_sizes = [[6e5, 1e11]], 
mu = [1e-7, 1e-9, "uniform"], 
gr_rates = None, changetimes = [[0, 8e4]] , mrca = None, migr = 1, 
migr_times = None, file_name = "tmp.lol", verbose = True)

print(t[0].loc[0:1,"mu"]) 
print(t[0].loc[0,"mu"]) 
```

File will look like this (values are random)
   samples_pop0           mu  tau  deme_sizes_pop0_t0  deme_sizes_pop0_t1  time_pop0_t1
0          3063 0.0    0              600000        100000000000  8.000000E+04
1          3063 0.0    0              600000        100000000000  8.000000E+04
2          3063 0.0    0              600000        100000000000  8.000000E+04
3          3063 0.0    0              600000        100000000000  8.000000E+04
4          3063 0.0    0              600000        100000000000  8.000000E+04
5          3063 0.0    0              600000        100000000000  8.000000E+04
6          3063 0.0    0              600000        100000000000  8.000000E+04
7          3063 0.0    0              600000        100000000000  8.000000E+04
8          3063 0.0    0              600000        100000000000  8.000000E+04
9          3063 0.0    0              600000        100000000000  8.000000E+04


Solved with commit #2cb1cb0cd30d402218be43485316bbe7dd54ec39

   samples_pop0           mu  tau  deme_sizes_pop0_t0  deme_sizes_pop0_t1  time_pop0_t1
0          3063 9.752064E-09    0              600000        100000000000  8.000000E+04
1          3063 2.784902E-08    0              600000        100000000000  8.000000E+04
2          3063 4.627848E-08    0              600000        100000000000  8.000000E+04
3          3063 1.712703E-08    0              600000        100000000000  8.000000E+04
4          3063 2.778999E-08    0              600000        100000000000  8.000000E+04
5          3063 7.967151E-08    0              600000        100000000000  8.000000E+04
6          3063 8.803903E-09    0              600000        100000000000  8.000000E+04
7          3063 8.181056E-08    0              600000        100000000000  8.000000E+04
8          3063 2.386673E-09    0              600000        100000000000  8.000000E+04
9          3063 4.816595E-08    0              600000        100000000000  8.000000E+04
